### ISSUE TITLE
Does not work. is this still being maintained

### ISSUE THREAD

**Issue by ciaron88** [Dziango/Twitch-Autorefresher-error-2000-chrome#1]
on Firefox 75.0 and this does not refresh twitch at any point

**Comment by Canejo** [comment]
I created pull request #2 to correct this error

**Comment by KraXen72** [comment]
check out this userscript i made that does exactly what this extension but more elegant: https://greasyfork.org/en/scripts/418450-autorefresh-twitch-on-error-2000

**Comment by Dziango** [comment]
It hasn't been maintained for a long time, but it's about to change :)

**Comment by KraXen72** [comment]
> check out this userscript i made that does exactly what this extension but more elegant: https://greasyfork.org/en/scripts/418450-autorefresh-twitch-on-error-2000

you can use my script and jsut make it an extension if you want :) the script sitll works

**Comment by Dziango** [comment]
@KraXen72 Thank you for the offer, however I really need to do it by myself :) Just having this trivial task to do is doing me wonders. Familiarizing me with the git workflow, teaching new programming concept and forcing to think for a bit and overcome some challenges. It's quite fun thing to do before bed :)

**Comment by KraXen72** [comment]
alright. if you want a challenge, try to get it to work using a mutationobserver. i currently have it through setTimeout, and thats not ideal but does the job for now. mutationobserver would be ideal but i couldn't get it to work

**Comment by Dziango** [comment]
@KraXen72 Mutationobserver works fine for me. Since I've set it up years ago I haven't had any issues with that. Can you clarify what is not working for u?

**Comment by KraXen72** [comment]
idk man it was pretty new at the time i made the script so i just have a setTimeout for like 2 seconds or something that calls itself and checks if the stream has died and if yes it pauses and plays the stream again. but it would be cool if you could get the detection working through a mutation observer, because it would restart intsantly and not potentially after 2 seconds.

**Comment by Dziango** [comment]
@KraXen72 that's how my code works. Take a look at it (https://github.com/Dziango/Twitch-Autorefresher-error-2000/blob/master/content.js) - once any change in the player is detected then I run FindError() function which determines if there's a need to refresh the stream or not. In other words FindError() does what it says it does - checks the player for an error.
No timeouts needed. It fires only when there is a change, no need to check manually every X seconds and waste browser resources.
