### ISSUE TITLE
doesent work

### ISSUE THREAD

**Issue by KraXen72** [Dziango/Twitch-Autorefresher-error-2000-chrome#3]
chrome 87. doesent refresh

**Comment by Makstuff** [comment]
Firefox 84, also doesn't do anything when I get error 2000.

**Comment by KraXen72** [comment]
since this is broken, i made a userscript that does this

https://greasyfork.org/en/scripts/418450-autorefresh-twitch-on-error-2000

**Comment by Makstuff** [comment]
@KraXen72 I installed the script, and today when I got an error 2000 again, it didn't do anything. I assume it works for you? Any idea what could be the reason?

**Comment by KraXen72** [comment]
it detect the darkness-0 overlay that happesn 99% of the times when you get an error 2000. it's not perfect but the element it was detecting previously caused that if you have frankerfacez, it would refresh every time you pause, so i had to change it. if you use the script, uninstall this extension, and tell me if the script works or not

**Comment by Makstuff** [comment]
I uninstalled the add-on even before I installed the script, so I guess that's not the issue.

Is it possible something's wrong with my setup? I'm using Tampermonkey on Firefox 84, and at least the other script I have set up (for changing line height of stack exchange website) works normally.

**Comment by KraXen72** [comment]
turn on the script, go to any livestream, open the console, and turn off your wifi, you should see a message in console saying something about error 2000 (my script outputs it). tell me if you see it or not.

**Comment by KraXen72** [comment]
hmm i tried it now and its broken, ill try to fix it

**Comment by Makstuff** [comment]
I get this: 

ERROR: Execution of script 'autorefresh twitch on error 2000' failed! MutationObserver.observe: Argument 1 is not an object.

**Comment by KraXen72** [comment]
i fixed it now, update from greasyfork and tell me if it works (turn off wifi and you will get error 2000, if it refreshes it works)

**Comment by Makstuff** [comment]
Yup, works like a charm. Thanks :)

**Comment by KraXen72** [comment]
np, glad to help. if it breaks again just comment here. btw, just tried it, also works in the background (if you are on a different tab)

**Comment by Makstuff** [comment]
Got another error 2000 just now (a real one, no simulation), and it didn't trigger. When testing it with turning off the internet connection it still refreshes, so seems these are two different things somehow? (So far I've never seen it trigger in a real situation, only in tests.)

**Comment by KraXen72** [comment]
man, i try to fix it everytime it doesen't work, now it works like 70-85% of the time on real errors, just update it from greasyfork reguraly i hope one day it works 100% of the time

**Comment by KraXen72** [comment]
if you know any javascript we can work on it together, but idk why it sometimes doesen't work... also, do you use bttv / frankerfacez? it should work with both just asking, because ffz had some problems

**Comment by Makstuff** [comment]
I don't know a lot about web programming, certainly not enough to contribute anything useful here. Guess the only thing I can do is give feedback and test things on my system. (Not using either bttv or frankerfacez.)

I'll install the update and report back the next time I see it work or fail on a real error. Probably gonna be a couple of days since I'll not get to watch a lot over Christmas. Merry Christmas btw :)

**Comment by KraXen72** [comment]
no problem, thanks a ton for reporting bugs, even thought this is a random person's repo for a broken extension :) Merry Christmas to you too!

**Comment by Makstuff** [comment]
Whee, error again, this time while I had another tab open and it was running in the background. Script did nothing. Added screenshots of console taken immediately after I noticed the error. Don't think theres anything useful in there, but still gonna post them just in case.

![1](https://user-images.githubusercontent.com/57408125/103143549-9afd2280-4718-11eb-9e5d-8ec43d017228.JPG)
![2](https://user-images.githubusercontent.com/57408125/103143552-9fc1d680-4718-11eb-838a-c4e1bb7ee938.JPG)

**Comment by KraXen72** [comment]
i'm pretty sure the script had some error at the start, and therefore wasn't running when the error 2000 occured. next time it occurs, try going as much up as you can, to see if the userscript throws any errors into the console. thanks for reporting this

**Comment by Makstuff** [comment]
Good guess it seems :) Same error as a few days ago, first console entry when opening a twitch tab is `ERROR: Execution of script 'autorefresh twitch on error 2000' failed! MutationObserver.observe: Argument 1 is not an object.`

Full error as output by the console in case there's anything useful in there:

> ERROR: Execution of script 'autorefresh twitch on error 2000' failed! MutationObserver.observe: Argument 1 is not an object. autorefresh twitch on error 2000.user.js:1:274
>     <anonymous> moz-extension://c241b624-ea2f-4ea9-9c41-8edb4703c217/userscripts/autorefresh twitch on error 2000.user.js?id=d0e16adb-123f-4113-af38-1d559a97fb28:1
>     <anonymous> moz-extension://c241b624-ea2f-4ea9-9c41-8edb4703c217/userscripts/autorefresh twitch on error 2000.user.js?id=d0e16adb-123f-4113-af38-1d559a97fb28:1
>     <anonymous> moz-extension://c241b624-ea2f-4ea9-9c41-8edb4703c217/userscripts/autorefresh twitch on error 2000.user.js?id=d0e16adb-123f-4113-af38-1d559a97fb28:42
>     <anonymous> moz-extension://c241b624-ea2f-4ea9-9c41-8edb4703c217/userscripts/autorefresh twitch on error 2000.user.js?id=d0e16adb-123f-4113-af38-1d559a97fb28:44
>     T eval:3
>     N eval:2
>     E_u eval:3
>     Ka eval line 1 > Function:61
>     create eval line 1 > Function:73
>     L eval line 1 > Function:12

Thanks for being so responsive as well btw ;) hope when this ever works there's a way to give it some visibility.

**Comment by KraXen72** [comment]
D.



ne 27. 12. 2020 o 1:03 Cimiteriophiliac <notifications@github.com>
napísal(a):

**Comment by KraXen72** [comment]
so the problem was, that if you didn't directly go to a streamers page, there was no video element and the script crashed. now i added a timeout, so it waits until the video element exists, and also a custom event listener that reloads the script if you navigate to a different twitch page (different streamer etc).
update from greasyfork.
this should solve all issues.

**Comment by KraXen72** [comment]
if you have any issues, feel free to report them.

**Comment by Makstuff** [comment]
The new version doesn't seem to react to the turning-off-internet test. Probably normal? In any case, I'll report back when I get a real error 2000 again.

**Comment by KraXen72** [comment]
the turning off test works for me, your console outputs from the script should look something like this:
when the page loads:
![image](https://user-images.githubusercontent.com/21956756/103227268-34515200-492e-11eb-8477-c0f6ce95967e.png)
after the fake error 2000 it should say "error2000" in console and refresh to the "no internet page" (since it refreshed you probably won't see the error2000 message in console, just the default firefox no internet page)
tell me if it directs you to the no internet page after you disconnect - without the script it would just stay on twitch

**Comment by KraXen72** [comment]
also i just got a real error 2000 and it instantly refreshed flawlessly... tell me if it works for you

**Comment by Makstuff** [comment]
Just tested all version of the script again with the turn off test, here's what happens:

**1.0, 1.1, 1.2, 1.3:** `ERROR: Execution of script 'autorefresh twitch on error 2000' failed! MutationObserver.observe: Argument 1 is not an object.`

**1.4:** Works normally, gives expected console output and refreshes

**1.5:** Does nothing, doesn't appear in console output at all, not even any error

I even tried **1.5** with Chrome since it appears that's what you are using, but just as in Firefox not a single console output.

Strange thing that **1.2** has worked in the turn off test before, and now gives an error at start.

**Comment by KraXen72** [comment]
the only thing i changed in 1.5 is that instead of ``www.twitch.tv/*`` it targets ``*://*twitch.tv/*``. you can use 1.4 if it works for you, 1.5 is litteraly the same thing but i guess firefox doesen't load it... if you could send the 1.4 code so i can make 1.6 the same as 1.4 since that works

**Comment by Makstuff** [comment]
1.4 has already failed at a real error once, but I guess I'll keep using it for a while and keep you updated, maybe this one time was bad luck or whatever.

Just a thought, maybe if you add the :// in front of the website, it expects the http(s) as well?

**Comment by KraXen72** [comment]
update from greasyfork please and tell me if it loads
for me it loads

**Comment by Makstuff** [comment]
Yup it loads. It spams the console with "waiting" five times per second or so, but it doesn't refresh.

**Comment by KraXen72** [comment]
i mean it shouldn't spam waiting if the video is running...

**Comment by Makstuff** [comment]
Nah but if I do the turn off test it does

**Comment by KraXen72** [comment]
lemme just install it on firefox and see

**Comment by KraXen72** [comment]
okay update shouldn't spam anymore

**Comment by Makstuff** [comment]
Yup doesn't spam, but the `ERROR: Execution of script 'autorefresh twitch on error 2000' failed! MutationObserver.observe: Argument 1 is not an object.` is back too.

**Comment by KraXen72** [comment]
ree

**Comment by Makstuff** [comment]
By the way, v1.6 refresh worked on both Firefox and Chrome now on second try, maybe I made a mistake when I tested it for the first time.

**Comment by KraXen72** [comment]
it works for me idk can you click on the error like where in the code is it.
![image](https://user-images.githubusercontent.com/21956756/103231946-73d16b80-4939-11eb-84eb-eeafead8b6e9.png)

**Comment by KraXen72** [comment]
yeah probs that

**Comment by KraXen72** [comment]
also what userscript manager are you using? it shouldn't matter but i use violentmonkey

**Comment by KraXen72** [comment]
also rip that one person who owns this github repo got so many issue replies lol

**Comment by Makstuff** [comment]
There's the fully expanded console, hope that's what you mean. Same error repeats a few times. Changed to Violentmonkey now just to check, so maybe that's why the error is worded slightly different than before.

![Capture](https://user-images.githubusercontent.com/57408125/103232381-957f2280-493a-11eb-9907-eee7f183d89a.JPG)

And don't worry about the repo owner, a person who stops maintaining such an essential extension doesn't deserve better ;)

**Comment by KraXen72** [comment]
ok try reinstalling and then send a screenshot of your console

**Comment by KraXen72** [comment]
update from greasyfork

**Comment by Makstuff** [comment]
Let me know if you need any more than this:

![Capture](https://user-images.githubusercontent.com/57408125/103240591-0af5ed80-4951-11eb-8370-78ec0a6ec5eb.JPG)

**Comment by KraXen72** [comment]
do you have discord? github messages take too long to deliver

**Comment by Cimiteriophiliac** [comment]
Don't use it normally, but it's Max51#9720
